### ISSUE TITLE
[Request] 0_userdata.0 ermöglichen

### ISSUE THREAD

**Issue by xCruziX** [ticaki/DWD-Pushwarnungen-iobroker#1]
Hallo, wäre schön, wenn man auch einen Pfad unter 0_userdata.0 eingeben könnte.

**Comment by ticaki** [comment]
Du meinst damit, dass du den Path von UWZ/DWD anpassen kannst?

**Comment by xCruziX** [comment]
Ich meine die gesamte Struktur, die erzeugt wird.
javascript.x.DWD_Script.Commands
javascript.x.DWD_Script.alert
javascript.x.DWD_Script.message

Diese hätte ich gerne unter 0_userdata.0

0_userdata.0.DWD_Script.Commands
0_userdata.0.DWD_Script.alert
0_userdata.0.DWD_Script.message

**Comment by ticaki** [comment]
ok baue ich morgen abend ein.

**Comment by xCruziX** [comment]
Ok, danke.
Vielleicht hilft das dabei:
https://github.com/xCruziX/DWD-Pushwarnungen-iobroker/blob/userdata/script.js

Hierbei funktioniert beides.
Einzig die subscriptions werden beim ersten Anlegen der States nicht korrekt abonniert, weil er nicht checkt, dass die States bereits da sind.

**Comment by ticaki** [comment]
Danke das hilft.  Habs übernommen.
Das 2 mal starten find ich eigentlich ok. Die Alternative die ich ausprobiert habe, war mir den Aufwand nicht wert. (letzter createState ruf in einem Callback ein setTimout(startScript()) auf. Vorher wurde das Script nach dem Aufruf vom letzten createState angehalten).
